name: purple
description: Graduation project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
#  basic_utils: ^4.2.2
  http: ^0.13.5
  flutter:
    sdk: flutter
  intl: ^0.17.0
  flutter_slidable: ^1.3.0
  email_validator: ^2.0.1
  flutter_rating_bar: ^4.0.1
  dropdown_button2: ^1.9.2
  cloud_firestore: ^4.3.1
  get_time_ago:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.20.0-nullsafety.3
  provider: ^5.0.0
  image_picker:
  path_provider:
  fl_chart: ^0.36.1
  url_launcher: ^6.1.2
  data_table_2: ^2.0.3
  firebase_auth: ^4.1.3
  get: ^4.6.5
  json_annotation:
  objectid: ^2.1.0
  im_stepper: any
  geolocator: ^8.2.1
#  flutter_launcher_icons: ^0.11.0
#
#flutter_icons:
#  image_path: "assets/images/log.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  table_calendar: ^3.0.8
  chatview:


  file_picker: ^5.2.5 # add new
  cloudinary_public: ^0.20.0 # add new



flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/log.png"
  adaptive_icon_background: #ffffff
  adaptive_icon_foreground: "assets/images/1024.png"

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/



  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
